![numpy-logo](numpy-logo.png)

#### Author: Mohammad Reza Mozaffari
Physics Group, University of Qom

In [1]:
import numpy as np

## Create NumPy Array

### one-dimensional arrays

In [2]:
a = np.array([5,-2, 11]) 
a

array([ 5, -2, 11])

<div>
<img src="imags/fig01.jpg" width="225"/>
</div>

In [3]:
print(type(a))
print(a.dtype) # dtype is a property.
print(a.ndim) # ndim is a property.
print(a.shape) # shape is a property

for i in range(len(a)):
    print("a[{}] = {}".format(i, a[i]))

<class 'numpy.ndarray'>
int64
1
(3,)
a[0] = 5
a[1] = -2
a[2] = 11


In [4]:
a = np.array([1., 2., 3.]) 
a

array([1., 2., 3.])

In [5]:
print(type(a))
print(a.dtype)
print(a.ndim)
print(a.shape)

for i in range(len(a)):
    print("a[{}] = {}".format(i, a[i]))

<class 'numpy.ndarray'>
float64
1
(3,)
a[0] = 1.0
a[1] = 2.0
a[2] = 3.0


In [6]:
a = np.array([1., 2., 3.], dtype=np.float128) # dtype sets the type of the array’s elements.
a

array([1., 2., 3.], dtype=float128)

In [7]:
print(type(a))
print(a.dtype)
print(a.ndim)
print(a.shape)

for i in range(len(a)):
    print("a[{}] = {}".format(i, a[i]))

<class 'numpy.ndarray'>
float128
1
(3,)
a[0] = 1.0
a[1] = 2.0
a[2] = 3.0


In [8]:
a = np.array([1, 2, 3], dtype=np.complex64) 
a

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

In [9]:
print(type(a))
print(a.dtype)
print(a.ndim)
print(a.shape)

for i in range(len(a)):
    print("a[{}] = ({}, {})".format(i, a[i].real, a[i].imag))

<class 'numpy.ndarray'>
complex64
1
(3,)
a[0] = (1.0, 0.0)
a[1] = (2.0, 0.0)
a[2] = (3.0, 0.0)


### two-dimensional arrays

In [10]:
b = np.array([[5,-2, 11], [7, 9,-3]])
b

array([[ 5, -2, 11],
       [ 7,  9, -3]])

<div>
<img src="imags/fig02.jpg" width="300"/>
</div>

In [11]:
print(type(b))
print(b.ndim)
print(b.dtype)
print(b.shape)

for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        print("b[{}, {}] = {}".format(i, j, b[i, j]))

<class 'numpy.ndarray'>
2
int64
(2, 3)
b[0, 0] = 5
b[0, 1] = -2
b[0, 2] = 11
b[1, 0] = 7
b[1, 1] = 9
b[1, 2] = -3


In [12]:
b = np.array([[1, 2, 3], [4, 5, 6]], dtype="float64") 
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
print(type(b))
print(b.ndim)
print(b.dtype)
print(b.shape)

for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        print("b[{}, {}] = {}".format(i, j, b[i, j]))

<class 'numpy.ndarray'>
2
float64
(2, 3)
b[0, 0] = 1.0
b[0, 1] = 2.0
b[0, 2] = 3.0
b[1, 0] = 4.0
b[1, 1] = 5.0
b[1, 2] = 6.0


In [14]:
b = np.array([[1, 2, 3], [4, 5, 6]], dtype="complex64") 
b

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [15]:
print(type(b))
print(b.ndim)
print(b.dtype)
print(b.shape)

for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        print("b[{}, {}] = ({}, {})".format(i, j, b[i, j].real, b[i, j].imag))

<class 'numpy.ndarray'>
2
complex64
(2, 3)
b[0, 0] = (1.0, 0.0)
b[0, 1] = (2.0, 0.0)
b[0, 2] = (3.0, 0.0)
b[1, 0] = (4.0, 0.0)
b[1, 1] = (5.0, 0.0)
b[1, 2] = (6.0, 0.0)


### zeros() function

In [16]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.shape)

a[3:7] = 2
a

<class 'numpy.ndarray'>
1
float64
(10,)


array([0., 0., 0., 2., 2., 2., 2., 0., 0., 0.])

In [18]:
a = np.zeros(10, dtype="int32")
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [19]:
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.shape)

a[3:7] = 5
a

<class 'numpy.ndarray'>
1
int32
(10,)


array([0, 0, 0, 5, 5, 5, 5, 0, 0, 0], dtype=int32)

In [20]:
a = np.zeros(10, dtype="complex64")
a

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j], dtype=complex64)

In [21]:
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.shape)

a[3:7] = 2.j
a

<class 'numpy.ndarray'>
1
complex64
(10,)


array([0.+0.j, 0.+0.j, 0.+0.j, 0.+2.j, 0.+2.j, 0.+2.j, 0.+2.j, 0.+0.j,
       0.+0.j, 0.+0.j], dtype=complex64)

### ones() function

In [22]:
b = np.ones(10, dtype="int32")
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [23]:
print(type(b))
print(b.ndim)
print(b.dtype)
print(b.shape)

b[3:7] = -6
b

<class 'numpy.ndarray'>
1
int32
(10,)


array([ 1,  1,  1, -6, -6, -6, -6,  1,  1,  1], dtype=int32)

In [24]:
b = np.ones(10, dtype="float64")
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
print(type(b))
print(b.ndim)
print(b.dtype)
print(b.shape)

b[3:7] = 2.5
b[:3] = 0.0
b[7:] = 0.0
b

<class 'numpy.ndarray'>
1
float64
(10,)


array([0. , 0. , 0. , 2.5, 2.5, 2.5, 2.5, 0. , 0. , 0. ])

In [26]:
b = np.ones(10, dtype=np.complex64)
b

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
       1.+0.j, 1.+0.j], dtype=complex64)

In [27]:
print(type(b))
print(b.ndim)
print(b.dtype)
print(b.shape)

<class 'numpy.ndarray'>
1
complex64
(10,)


In [28]:
b = np.ones((2, 5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
print(type(b))
print(b.ndim)
print(b.dtype)
print(b.shape)

for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        print("b[{}, {}] = {}".format(i, j, b[i, j]))

<class 'numpy.ndarray'>
2
float64
(2, 5)
b[0, 0] = 1.0
b[0, 1] = 1.0
b[0, 2] = 1.0
b[0, 3] = 1.0
b[0, 4] = 1.0
b[1, 0] = 1.0
b[1, 1] = 1.0
b[1, 2] = 1.0
b[1, 3] = 1.0
b[1, 4] = 1.0


In [30]:
b = np.ones((2, 5), dtype=np.float64)
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
print(type(b))
print(b.ndim)
print(b.dtype)
print(b.shape)

for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        print("b[{}, {}] = {}".format(i, j, b[i, j]))

<class 'numpy.ndarray'>
2
float64
(2, 5)
b[0, 0] = 1.0
b[0, 1] = 1.0
b[0, 2] = 1.0
b[0, 3] = 1.0
b[0, 4] = 1.0
b[1, 0] = 1.0
b[1, 1] = 1.0
b[1, 2] = 1.0
b[1, 3] = 1.0
b[1, 4] = 1.0


### arange() function

In [32]:
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a = np.arange(10, 0, -2)
a

array([10,  8,  6,  4,  2])

In [34]:
a = np.arange(0.0, 10.0)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
a = np.arange(0, 10, dtype=np.float64)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
a = np.arange(0.0, 10.0, 1.0)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [37]:
a = np.arange(0.0, 10.0, 0.1)
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

### linspace() function

In [38]:
b = np.linspace(0, 10, 11, dtype="int32")
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [39]:
b = np.linspace(0, 10, 11)
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### one-dimensional array slicing

In [40]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<div>
<img src="imags/fig06.jpg" width="400"/>
</div>

In [41]:
a[:5]

array([1, 2, 3, 4, 5])

<div>
<img src="imags/fig07.jpg" width="400"/>
</div>

In [42]:
a[5:]

array([ 6,  7,  8,  9, 10])

<div>
<img src="imags/fig08.jpg" width="400"/>
</div>

In [43]:
a[3:7]

array([4, 5, 6, 7])

<div>
<img src="imags/fig10.jpg" width="400"/>
</div>

In [44]:
a[::2]

array([1, 3, 5, 7, 9])

<div>
<img src="imags/fig11.jpg" width="400"/>
</div>

In [45]:
a[9::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

<div>
<img src="imags/fig12.jpg" width="400"/>
</div>

### two-dimensional array slicing

In [46]:
a = np.array([[5, -2, 11], [7, 9, -3], [-1, 4, 5]])
a

array([[ 5, -2, 11],
       [ 7,  9, -3],
       [-1,  4,  5]])

<div>
<img src="imags/fig03.jpg" width="300"/>
</div>

In [47]:
a[1, :]

array([ 7,  9, -3])

<div>
<img src="imags/fig04.jpg" width="300"/>
</div>

In [48]:
a[:,1:]

array([[-2, 11],
       [ 9, -3],
       [ 4,  5]])

<div>
<img src="imags/fig05.jpg" width="300"/>
</div>

In [49]:
a[:2,1:]

array([[-2, 11],
       [ 9, -3]])

<div>
<img src="imags/fig13.jpg" width="300"/>
</div>

In [50]:
a[::2,::2]

array([[ 5, 11],
       [-1,  5]])

<div>
<img src="imags/fig14.jpg" width="300"/>
</div>

### Fancy Indexing

In [51]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
indices = [2, 3, 4]
a[indices]

array([3, 4, 5])

<div>
<img src="imags/fig15.jpg" width="400"/>
</div>

In [53]:
a[[1, 2, 6, 9]]

array([ 2,  3,  7, 10])

<div>
<img src="imags/fig16.jpg" width="400"/>
</div>

### Boolean Indexing

In [54]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
boolean_mask = a%2 == 0
print(boolean_mask)
a[boolean_mask]

[False  True False  True False  True False  True False  True]


array([ 2,  4,  6,  8, 10])

In [56]:
boolean_mask = a%2 != 0
print(boolean_mask)
a[boolean_mask]


[ True False  True False  True False  True False  True False]


array([1, 3, 5, 7, 9])

In [57]:
boolean_mask = (a>2) & (a<9)
print(boolean_mask)
a[boolean_mask]

[False False  True  True  True  True  True  True False False]


array([3, 4, 5, 6, 7, 8])

In [58]:
boolean_mask = (a>2) & (a<9)
print(~boolean_mask)
a[~boolean_mask]

[ True  True False False False False False False  True  True]


array([ 1,  2,  9, 10])

### copy

In [59]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
b = a[:3,1:]
b

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [61]:
b[0,0] =-20
b

array([[-20,   3,   4],
       [  6,   7,   8],
       [ 10,  11,  12]])

In [62]:
a

array([[  1, -20,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16]])

In [63]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [64]:
c = a[:3,1:].copy()
c

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [65]:
c[0, 0] =-20
c

array([[-20,   3,   4],
       [  6,   7,   8],
       [ 10,  11,  12]])

In [66]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### sum() function

In [67]:
a = np.array([1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [68]:
s = 0
for i in range(len(a)):
    s = s + a[i]
print("s = ", s)

s =  55.0


In [69]:
np.sum(a)

55.0

In [70]:
a.sum()

55.0

In [71]:
s = 0
for i in range(2, 7):
    s = s + a[i]
print("s = ", s)

s =  25.0


In [72]:
a[2:7].sum()

25.0

In [73]:
np.sum(a[2:7])

25.0

In [74]:
a = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [75]:
s = 0
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        s = s + a[i,j]
print("sum = ", s)

sum =  45.0


In [76]:
np.sum(a)

45.0

In [77]:
a.sum()

45.0

In [78]:
a.sum(axis=0)

array([12., 15., 18.])

In [79]:
np.sum(a, axis=1)

array([ 6., 15., 24.])

In [80]:
a[1:, 1:]

array([[5., 6.],
       [8., 9.]])

In [81]:
a[1:, 1:].sum(axis=0)

array([13., 15.])

### mean() function

In [82]:
a = np.array([1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [83]:
s = 0
for i in range(len(a)):
    s = s + a[i]
print("sum = ", s)

mean = s/float(len(a))
print("mean = ", mean)

sum =  55.0
mean =  5.5


In [84]:
a.mean()

5.5

In [85]:
np.mean(a)

5.5

In [86]:
a[2:7]

array([3., 4., 5., 6., 7.])

In [87]:
a[2:7].sum()

25.0

In [88]:
a[2:7].mean()

5.0

In [89]:
a = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [90]:
s = 0
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        s = s + a[i,j]
print("sum = ", s)

mean = s/float(a.shape[0]*a.shape[1])
print("mean = ", mean)

sum =  45.0
mean =  5.0


In [91]:
np.mean(a)

5.0

In [92]:
a.mean()

5.0

In [93]:
a.mean(axis=0)

array([4., 5., 6.])

In [94]:
a.mean(axis=1)

array([2., 5., 8.])

In [95]:
a[1:, 1:]

array([[5., 6.],
       [8., 9.]])

In [96]:
a[1:, 1:].mean(axis=0)

array([6.5, 7.5])

### var() function

In [97]:
a = np.array([1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [98]:
np.sum(np.power(a - a.mean(), 2))/float(len(a))

8.25

In [99]:
np.var(a)

8.25

In [100]:
a.var()

8.25

In [101]:
a[2:7]

array([3., 4., 5., 6., 7.])

In [102]:
np.sum(np.power(a[2:7]- a[2:7].mean(), 2))/float(len(a[2:7]))

2.0

In [103]:
np.var(a[2:7])

2.0

In [104]:
a = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [105]:
np.sum(np.power(a - a.mean(), 2))/float(a.shape[0]*a.shape[1])

6.666666666666667

In [106]:
a.var()

6.666666666666667

In [107]:
a.var(axis=0)

array([6., 6., 6.])

In [108]:
a.var(axis=1)

array([0.66666667, 0.66666667, 0.66666667])

### std() function

In [109]:
a = np.array([1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [110]:
np.sqrt(np.sum(np.power(a - a.mean(), 2))/float(len(a)))

2.8722813232690143

In [111]:
np.std(a)

2.8722813232690143

In [112]:
a.std()

2.8722813232690143

In [113]:
a[2:7]

array([3., 4., 5., 6., 7.])

In [114]:
np.sqrt(np.sum(np.power(a[2:7]- a[2:7].mean(), 2))/float(len(a[2:7])))

1.4142135623730951

In [115]:
np.std(a[2:7])

1.4142135623730951

In [116]:
a = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [117]:
np.sqrt(np.sum(np.power(a - a.mean(), 2))/float(a.shape[0]*a.shape[1]))

2.581988897471611

In [118]:
a.std()

2.581988897471611

### prod() function

In [119]:
a = np.array([1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [120]:
p = 1
for i in range(len(a)):
    p = p * a[i]
p

3628800.0

In [121]:
np.prod(a)

3628800.0

In [122]:
a.prod()

3628800.0

In [123]:
p = 1
for i in range(2, 7):
    p = p * a[i]
p

2520.0

In [124]:
a[2:7].prod()

2520.0

In [125]:
a = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [126]:
p = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        p = p * a[i, j]
p

362880.0

In [127]:
np.prod(a)

362880.0

In [128]:
a.prod()

362880.0

In [129]:
a.prod(axis=0)

array([ 28.,  80., 162.])

In [130]:
a.prod(axis=1)

array([  6., 120., 504.])

In [131]:
a[1:, 1:].prod(axis=0)

array([40., 54.])

### amin() and amax() function

In [132]:
a = np.array([1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [133]:
np.amin(a)

1.0

In [134]:
np.amin(a[2:7])

3.0

In [135]:
np.amax(a)

10.0

In [136]:
np.amax(a[2:7])

7.0

In [137]:
a = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [138]:
np.amin(a)

1.0

In [139]:
np.amin(a, axis=0)

array([1., 2., 3.])

In [140]:
np.amin(a[1:, 1:], axis=0)

array([5., 6.])

In [141]:
np.amax(a)

9.0

In [142]:
np.amax(a, axis=1)

array([3., 6., 9.])

In [143]:
np.amax(a[1:, 1:], axis=1)

array([6., 9.])

### reshape() function

In [144]:
a = np.array([1.2, 2.3, 3.4, 4.5])
a

array([1.2, 2.3, 3.4, 4.5])

In [145]:
b = a.reshape((2,2))
b

array([[1.2, 2.3],
       [3.4, 4.5]])

In [146]:
b = a.reshape((4, 1))
b

array([[1.2],
       [2.3],
       [3.4],
       [4.5]])

### transpose() function

In [147]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [148]:
a.transpose() # no effect on a 1-D array

array([1, 2, 3])

In [149]:
np.transpose(a) # no effect on a 1-D array

array([1, 2, 3])

In [150]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [151]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [152]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [153]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [154]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [155]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

### sort() function

In [156]:
a = np.array([2.3, 1.2, 4.5, 3.4])
a

array([2.3, 1.2, 4.5, 3.4])

In [157]:
np.sort(a) #increae

array([1.2, 2.3, 3.4, 4.5])

In [158]:
np.sort(a)[::-1] # decrease

array([4.5, 3.4, 2.3, 1.2])

In [159]:
a = np.array([[2.3, 1.2], [4.5, 3.4]])
a

array([[2.3, 1.2],
       [4.5, 3.4]])

In [160]:
b = np.sort(a)
b

array([[1.2, 2.3],
       [3.4, 4.5]])

In [161]:
b = np.sort(a, axis = 0)
b

array([[2.3, 1.2],
       [4.5, 3.4]])

In [162]:
b = np.sort(a, axis = 0)[::-1]
b

array([[4.5, 3.4],
       [2.3, 1.2]])

In [163]:
b = np.sort(a, axis = 1)
b

array([[1.2, 2.3],
       [3.4, 4.5]])

In [164]:
b = np.sort(a, axis = 1)[::-1]
b

array([[3.4, 4.5],
       [1.2, 2.3]])

### flatten() method

In [165]:
a = np.array([[1.2, 2.3], [3.4, 4.5]])
a

array([[1.2, 2.3],
       [3.4, 4.5]])

In [166]:
a.flatten()

array([1.2, 2.3, 3.4, 4.5])

In [167]:
a.flatten(order="F") # axis = 0

array([1.2, 3.4, 2.3, 4.5])

In [168]:
a.flatten(order="C") # axis = 1

array([1.2, 2.3, 3.4, 4.5])

### ravel() function

In [169]:
a = np.array([[1.2, 2.3], [3.4, 4.5]])
a

array([[1.2, 2.3],
       [3.4, 4.5]])

In [170]:
np.ravel(a) # equal with a.flatten()

array([1.2, 2.3, 3.4, 4.5])

In [171]:
a.ravel() # equal with a.flatten()

array([1.2, 2.3, 3.4, 4.5])

Note: The flatten() method creates a copy of an input array while the ravel() function creates a view of the array. 

In [172]:
a = np.array([[1.2, 2.3], [3.4, 4.5]])
a

array([[1.2, 2.3],
       [3.4, 4.5]])

In [173]:
b = a.ravel()
b

array([1.2, 2.3, 3.4, 4.5])

In [174]:
b[0] =-1.2
b

array([-1.2,  2.3,  3.4,  4.5])

In [175]:
a.ravel()

array([-1.2,  2.3,  3.4,  4.5])

In [176]:
a = np.array([[1.2, 2.3], [3.4, 4.5]])
a

array([[1.2, 2.3],
       [3.4, 4.5]])

In [177]:
b = a.flatten()
b

array([1.2, 2.3, 3.4, 4.5])

In [178]:
b[0] =-1.2
b

array([-1.2,  2.3,  3.4,  4.5])

In [179]:
a.flatten()

array([1.2, 2.3, 3.4, 4.5])

### add() function

In [180]:
a = np.array([1., 2., 3.])
a

array([1., 2., 3.])

In [181]:
b = np.array([4., 5., 6.])
b

array([4., 5., 6.])

In [182]:
a + b

array([5., 7., 9.])

In [183]:
np.add(a, b)

array([5., 7., 9.])

In [184]:
a = np.array([[1., 2.], [3., 4.]])
a

array([[1., 2.],
       [3., 4.]])

In [185]:
b = np.array([[5., 6.], [7., 8.]])
b

array([[5., 6.],
       [7., 8.]])

In [186]:
a + b

array([[ 6.,  8.],
       [10., 12.]])

In [187]:
np.add(a, b)

array([[ 6.,  8.],
       [10., 12.]])

### subtract() function

In [188]:
a = np.array([1., 2., 3.])
a

array([1., 2., 3.])

In [189]:
b = np.array([4., 5., 6.])
b

array([4., 5., 6.])

In [190]:
a - b

array([-3., -3., -3.])

In [191]:
np.subtract(a, b)

array([-3., -3., -3.])

In [192]:
a = np.array([[1., 2.], [3., 4.]])
a

array([[1., 2.],
       [3., 4.]])

In [193]:
b = np.array([[5., 6.], [7., 8.]])
b

array([[5., 6.],
       [7., 8.]])

In [194]:
a - b

array([[-4., -4.],
       [-4., -4.]])

In [195]:
np.subtract(a, b)

array([[-4., -4.],
       [-4., -4.]])

### multiply() function

In [196]:
a = np.array([1., 2., 3.])
a

array([1., 2., 3.])

In [197]:
b = np.array([4., 5., 6.])
b

array([4., 5., 6.])

In [198]:
a * b

array([ 4., 10., 18.])

In [199]:
np.multiply(a, b)

array([ 4., 10., 18.])

In [200]:
a = np.array([[1., 2.], [3., 4.]])
a

array([[1., 2.],
       [3., 4.]])

In [201]:
b = np.array([[5., 6.], [7., 8.]])
b

array([[5., 6.],
       [7., 8.]])

In [202]:
a * b

array([[ 5., 12.],
       [21., 32.]])

In [203]:
np.multiply(a, b)

array([[ 5., 12.],
       [21., 32.]])

### divide() function

In [204]:
a = np.array([1., 2., 3.])
a

array([1., 2., 3.])

In [205]:
b = np.array([4., 5., 6.])
b

array([4., 5., 6.])

In [206]:
a / b

array([0.25, 0.4 , 0.5 ])

In [207]:
np.divide(a, b)

array([0.25, 0.4 , 0.5 ])

In [208]:
a = np.array([[1., 2.], [3., 4.]])
a

array([[1., 2.],
       [3., 4.]])

In [209]:
b = np.array([[5., 6.], [7., 8.]])
b

array([[5., 6.],
       [7., 8.]])

In [210]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [211]:
np.divide(a, b)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

### concatenate() function

In [212]:
a = np.array([1., 2., 3.])
a

array([1., 2., 3.])

In [213]:
b = np.array([4., 5., 6., 7., 8.])
b

array([4., 5., 6., 7., 8.])

In [216]:
np.concatenate((a, b))

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [217]:
np.concatenate((b, a))

array([4., 5., 6., 7., 8., 1., 2., 3.])

In [218]:
np.concatenate((b[::-1], a[::-1]))

array([8., 7., 6., 5., 4., 3., 2., 1.])

In [220]:
np.sort(np.concatenate((b, a)))

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [222]:
np.sort(np.concatenate((b, a)))[::-1]

array([8., 7., 6., 5., 4., 3., 2., 1.])

In [223]:
a = np.array([[1., 2.], [3., 4.]])
a

array([[1., 2.],
       [3., 4.]])

In [228]:
b = np.array([[5., 6.], [7., 8.]])
b

array([[5., 6.],
       [7., 8.]])

In [231]:
np.concatenate((a, b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [232]:
np.concatenate((a, b), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [233]:
np.concatenate((a, b), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

### stack() function

In [234]:
a = np.array([1., 2., 3.])
a

array([1., 2., 3.])

In [235]:
b = np.array([4., 5., 6.])
b

array([4., 5., 6.])

In [246]:
print("stack:\n", np.stack((a, b)))
print("concatenate:\n", np.concatenate((a, b)))

stack:
 [[1. 2. 3.]
 [4. 5. 6.]]
concatenate:
 [1. 2. 3. 4. 5. 6.]


In [245]:
print("stack:\n", np.stack((a, b)).shape)
print("concatenate:\n", np.concatenate((a, b)).shape)

stack:
 (2, 3)
concatenate:
 (6,)


In [247]:
np.stack((a, b), axis=0)

array([[4., 5., 6.],
       [1., 2., 3.]])

In [249]:
np.stack((a, b), axis=1)

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [250]:
a = np.array([1., 2., 3.])
a

array([1., 2., 3.])

In [251]:
b = np.array([4., 5.])
b

array([4., 5.])

In [253]:
np.stack((a, b)) # Error: not same shape arrays

ValueError: all input arrays must have the same shape

In [254]:
a = np.array([[1., 2.], [3., 4.]])
a

array([[1., 2.],
       [3., 4.]])

In [255]:
b = np.array([[5., 6.], [7., 8.]])
b

array([[5., 6.],
       [7., 8.]])

In [257]:
np.stack((a, b))

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [261]:
np.stack((a, b), axis=0)

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [262]:
np.vstack((a, b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [260]:
np.stack((a, b), axis=1)

array([[[1., 2.],
        [5., 6.]],

       [[3., 4.],
        [7., 8.]]])

### vstack() function

In [263]:
a = np.array([1., 2., 3.])
a

array([1., 2., 3.])

In [265]:
b = np.array([4., 5., 5.])
b

array([4., 5., 5.])

In [269]:
np.stack((a, b))

array([[1., 2., 3.],
       [4., 5., 5.]])

In [270]:
np.stack((a, b),axis=0)

array([[1., 2., 3.],
       [4., 5., 5.]])

In [266]:
np.vstack((a, b))

array([[1., 2., 3.],
       [4., 5., 5.]])

In [271]:
a = np.array([[1., 2.], [3., 4.]])
a

array([[1., 2.],
       [3., 4.]])

In [272]:
b = np.array([[5., 6.], [7., 8.]])
b

array([[5., 6.],
       [7., 8.]])

In [273]:
np.stack((a, b))

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [275]:
np.vstack((a, b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [276]:
np.concatenate((a, b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [277]:
np.concatenate((a, b), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

### hstack() function

In [279]:
a = np.array([1., 2., 3.])
a

array([1., 2., 3.])

In [284]:
b = np.array([4., 5., 6.])
b

array([4., 5., 6.])

In [285]:
np.concatenate((a, b))

array([1., 2., 3., 4., 5., 6.])

In [286]:
np.hstack((a, b))

array([1., 2., 3., 4., 5., 6.])

In [287]:
a = np.array([[1., 2.], [3., 4.]])
a

array([[1., 2.],
       [3., 4.]])

In [288]:
b = np.array([[5., 6.], [7., 8.]])
b

array([[5., 6.],
       [7., 8.]])

In [294]:
np.concatenate((a, b), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [293]:
np.hstack((a, b))

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])